# Main Project
- Name- Jyotikrishna Behera
- Branch- CSE
- Sic no.- 20BCSB33
## Objective : 
####Given a dataset about different conditions of a patient and taking it into account we have to train a model that will predict whether the chances of getting a heart attack is high or low. 

# Part A : Data preprocessing
##### Step 1 : Importing libraries


In [56]:
import numpy as np  #for numeric calculation
import pandas as pd #for working with data
import tensorflow as tf #deep learning framework

In [57]:
dataset = pd.read_csv("Heart.csv") #reading the dataset

In [58]:
dataset #visualize the dataset

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

##### Step 2: To create Feature Matrix(x) and Dependent variable vector(y)

In [59]:
x=dataset.iloc[:,:-1].values 
y=dataset.iloc[:,-1:].values #it is dependent on x

In [60]:
y

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

##### Step 3: Replacing Missing Data(by using the average)

In [61]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean') #the missing data is nan(not a number)
imputer.fit(x)
x=imputer.transform(x)

##### Step 4: Splitting the dataset into training and test sets

In [62]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)
 #we r dividing data into train n test set randomly in ratio 8:2

##### Step 5: Scaling the dataset (to avoid baised model towards larger value)

In [63]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.fit_transform(xtest)

In [64]:
xtest

array([[ 0.9194768 , -1.33143805, -0.86574938,  1.52235455, -1.5417599 ,
        -0.41602515, -0.92493962, -0.25525849, -0.75106762,  3.69304024,
        -2.16628237,  2.0851727 ,  0.96629063],
       [ 0.23547577,  0.75106762,  0.07729905, -0.14385886, -0.46790189,
        -0.41602515, -0.92493962,  0.64018504, -0.75106762, -0.80087166,
         1.01789171, -0.67994762,  0.96629063],
       [-0.67652561,  0.75106762, -0.86574938, -0.14385886,  0.1914846 ,
         2.40370085, -0.92493962, -0.00652418,  1.33143805, -0.80087166,
         1.01789171,  1.16346593,  0.96629063],
       [ 0.69147646,  0.75106762, -0.86574938, -0.14385886, -0.75049611,
        -0.41602515, -0.92493962, -0.90196771,  1.33143805,  0.93870714,
        -0.57419533,  1.16346593,  0.96629063],
       [-0.44852527,  0.75106762, -0.86574938,  0.96695008, -0.05343038,
        -0.41602515, -0.92493962, -1.10095516, -0.75106762,  1.08367204,
        -0.57419533, -0.67994762,  0.96629063],
       [ 1.03347698,  0.751067

# Part B: Build the Model
##### Step 1: Training the model

In [65]:
t1=tf.keras.models.Sequential()

In [66]:
#adding a hidden layer
# t1.add(tf.keras.layers.Dense(units=4,activation='relu'))
#adding a hidden layer
# t1.add(tf.keras.layers.Dense(units=2,activation='relu'))
# #adding a hidden layer
# t1.add(tf.keras.layers.Dense(units=2,activation='relu'))
#o/p layer
t1.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

##### Step 2: compile the model

In [67]:
t1.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

##### Step 3: training the model

In [68]:
t1.fit(xtrain,ytrain,epochs=200)

Epoch 1/200
8/8 [==============================] - 0s 889us/step - loss: 0.6861 - accuracy: 0.6446
Epoch 2/200
8/8 [==============================] - 0s 992us/step - loss: 0.6776 - accuracy: 0.6446
Epoch 3/200
8/8 [==============================] - 0s 880us/step - loss: 0.6691 - accuracy: 0.6446
Epoch 4/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6612 - accuracy: 0.6570
Epoch 5/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6532 - accuracy: 0.6570
Epoch 6/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6456 - accuracy: 0.6612
Epoch 7/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6383 - accuracy: 0.6694
Epoch 8/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6313 - accuracy: 0.6777
Epoch 9/200
8/8 [==============================] - 0s 1ms/step - loss: 0.6246 - accuracy: 0.6818
Epoch 10/200
8/8 [==============================] - 0s 996us/step - loss: 0.6175 - accuracy: 0.6777
Epoch 11/200
8/8 [===

8/8 [==============================] - 0s 871us/step - loss: 0.3366 - accuracy: 0.8636
Epoch 165/200
8/8 [==============================] - 0s 794us/step - loss: 0.3363 - accuracy: 0.8636
Epoch 166/200
8/8 [==============================] - 0s 872us/step - loss: 0.3360 - accuracy: 0.8636
Epoch 167/200
8/8 [==============================] - 0s 623us/step - loss: 0.3357 - accuracy: 0.8636
Epoch 168/200
8/8 [==============================] - 0s 996us/step - loss: 0.3354 - accuracy: 0.8636
Epoch 169/200
8/8 [==============================] - 0s 629us/step - loss: 0.3352 - accuracy: 0.8636
Epoch 170/200
8/8 [==============================] - 0s 872us/step - loss: 0.3349 - accuracy: 0.8636
Epoch 171/200
8/8 [==============================] - 0s 624us/step - loss: 0.3346 - accuracy: 0.8636
Epoch 172/200
8/8 [==============================] - 0s 747us/step - loss: 0.3343 - accuracy: 0.8636
Epoch 173/200
8/8 [==============================] - 0s 689us/step - loss: 0.3341 - accuracy: 0.8636
Epoc

##### Step 4: testing model

In [69]:
y1=t1.predict(xtest)

In [70]:
y1

array([[0.01220465],
       [0.7403697 ],
       [0.11667201],
       [0.01570466],
       [0.07268274],
       [0.00932115],
       [0.02247483],
       [0.5618081 ],
       [0.01187217],
       [0.9823154 ],
       [0.41653585],
       [0.18304104],
       [0.78551364],
       [0.34817305],
       [0.4606213 ],
       [0.9133874 ],
       [0.9854876 ],
       [0.04670531],
       [0.6260001 ],
       [0.8348761 ],
       [0.9735406 ],
       [0.05006421],
       [0.7891606 ],
       [0.97259843],
       [0.9645794 ],
       [0.85503685],
       [0.01166826],
       [0.98216164],
       [0.888324  ],
       [0.98340094],
       [0.9519578 ],
       [0.88855636],
       [0.77038133],
       [0.76038265],
       [0.06268361],
       [0.47142538],
       [0.14514014],
       [0.3913305 ],
       [0.6767818 ],
       [0.07135892],
       [0.93318653],
       [0.06079546],
       [0.23291203],
       [0.00684318],
       [0.6058301 ],
       [0.8479611 ],
       [0.31917286],
       [0.739

##### Step 5: Converting the output into boolean (true if >0.5 and false if less)

In [71]:
y1=(y1>0.5)
y1

array([[False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False]])

In [72]:
from sklearn.preprocessing import LabelEncoder #Encoding the true false as 1 and 0
le= LabelEncoder()
y1=le.fit_transform(y1)
y1

C:\Users\biswas\.conda\envs\tensor\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0], dtype=int64)

In [74]:
print(np.concatenate((y1.reshape(len(y1),1),ytest.reshape(len(ytest),1)),1))
# to visualize the ytest and y predicted side-by-side

[[0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 1]]


##### Step 6:  performance matrix ( to know the accuracy )

In [75]:
from sklearn.metrics import confusion_matrix, accuracy_score , precision_score 
cm= confusion_matrix(ytest,y1)
print(cm)
print(accuracy_score(ytest,y1))
print(precision_score(ytest,y1))

[[20 10]
 [ 6 25]]
0.7377049180327869
0.7142857142857143
